### ISSUE TITLE
Wildcard imports not supported

### ISSUE THREAD

**Issue by LauchInterceptor** [jo2/dependency-tree#1]

**Comment by LauchInterceptor** [comment]
Should wildcard imports be resolved as a dependency to the package or as multiple dependencies to the files contained in the package?

**Comment by jo2** [comment]
Dependency Tree handles dependencies from one source file to the next so wildcard dependencies should be handled as dependencies to each file in that package. Only for structuring purposes the dependencies are grouped in each package.
